### ISSUE TITLE
Make functions work with API from @naustica

### ISSUE THREAD

**Issue by bganglia** [bganglia/unpaywall-python#12]
The caching class / convenience functions from this package should be incorporated into this codebase from @naustica:

https://github.com/naustica/unpywall

**Comment by naustica** [comment]
Does it make sense to combine the _fetch and get_df methods with your cache?

**Comment by bganglia** [comment]
@naustica Yes, maybe _fetch could use cache.get instead of requests.get. 

The cache class would have to be changed a little bit, maybe to accept a URL instead of a DOI. I can make these changes if you would like, or you could too.

Also, the changes in ``merge_codebases`` look good. If you would like to merge them into master, that would be great.

**Comment by bganglia** [comment]
Actually, do you think that there are other steps left to make the codebases harmonize better?

Now that I think about it, I should probably change the old unpaywall-python functions to be called more like your functions, with a list of dois.

**Comment by naustica** [comment]
@bganglia I would suggest to only put releases into master.  But we could merge and test the current code in a "development" branch, if you like. It would also be good if you could adjust the caching class. Could you also check if your code works? I only checked mine so far.

**Comment by bganglia** [comment]
@bganglia Thanks, a "development" branch sounds like a good idea. 

I will go ahead and adjust the caching class and make sure everything works.

**Comment by bganglia** [comment]
@naustica Ok, I changed UnpaywallCache and _fetch to work together, so I am going to go ahead and push those changes

My functions are broken now though. Fixing that

**Comment by naustica** [comment]
@bganglia I like the caching function very much. But a function to clean or to ignore the cache would be a nice improvement! Also, I think i fixed your broken functions. I will push my code now.

**Comment by bganglia** [comment]
@naustica Ok, thanks. I will add that.

**Comment by naustica** [comment]
How did you deal with connection errors before? Were they ignored or would they have led to an abort?

**Comment by bganglia** [comment]
@naustica Good question. Before, they would have led to an abort.

If errors == 'ignore', do you think it is better to store the request, errors and all, or to not store it and just request it again next time?

Actually, better yet, what do you think of an argument that would fail to store requests on error?

**Comment by bganglia** [comment]
On the one hand, storing requests that raise errors could lead to network errors being repeated. On the other hand, not storing them could lead to repeated malformed requests. Maybe there should be a counter - try again for the first 3 calls, then don't request again. What do you think?

**Comment by naustica** [comment]
Maybe it is a good idea to store dois from faulty connections and print them out after execution (like a report). I would not save the request object in that case.

**Comment by bganglia** [comment]
@naustica Ok. I will add that to my PR with upgrades to the cache

**Comment by naustica** [comment]
@bganglia I updated the README file. Can you take a look and add your stuff?

**Comment by bganglia** [comment]
@naustica Yes, thanks for letting me know. I guess I will add a section after "Pandas integration"

**Comment by naustica** [comment]
@bganglia I would put the branch into master when youre done with the feature to ignore the cache. I would also do a small release on pypi. I think, the complete infrastructure would be in place then. 

I think you have to hide your project on pypi so that there is no confusion. I also have to hide my original unpywall repo.

**Comment by naustica** [comment]
@bganglia By the way, I gave you access to the unpywall project on pypi

**Comment by naustica** [comment]
@bganglia We should also think about a changelog.

**Comment by bganglia** [comment]
@naustica Thanks for that. Yes, I will go ahead and hide unpaywallpython on pypi. [This tweet](https://twitter.com/GangliaB/status/1247355756418138112) is a little regrettable now, but I guess it is OK.

Yes, a changelog is a good idea. I think that it would make sense to use your original code as the reference point for the changes. I guess we can each explain the changes from our respective parts.

I will try to wrap up the changes to the cache tonight or tomorrow morning.

**Comment by bganglia** [comment]
@naustica Also I added the beginning of some documentation for my functions to the README.md

**Comment by naustica** [comment]
@bganglia thanks! We should also use github releases to document changes. 

Twitter: You could possibly post a new tweet below it.

**Comment by naustica** [comment]
@bganglia I think the merge was successful. I guess we can close this issue now. Can you delete the other branches unless you still need them? Next, I would suggest to write unittests to get a coverage of > 80%.

**Comment by bganglia** [comment]
@naustica Yes, I will go ahead and delete them. What target date would you like for the unittests?
