### ISSUE TITLE
Add badges to README

### ISSUE THREAD

**Issue by naustica** [bganglia/unpaywall-python#19]
I think, we can use badges from https://shields.io/.

**Comment by naustica** [comment]
repo name needs to be updated for badges to display properly (-> unpywall). Some are only configured for the master branch.

**Comment by naustica** [comment]
@bganglia can you get the travis badge up and running?

**Comment by naustica** [comment]
@bganglia ok I updated the build badge, but I noticed a delay loading badges from shields.io

**Comment by bganglia** [comment]
@naustica Sorry about the delay. Did you want me to do something about the travis badge? I have not tried setting up badges yet.

Also, I am fine with renaming the repo

**Comment by naustica** [comment]
@bganglia I would rename the repo when we have our first release. The travis badge should now be properly integrated (is pointing to master).

Also, I think that the delayed loading of the badges is only a temporary problem.
