### ISSUE TITLE
Add function to download PDF to file

### ISSUE THREAD

**Issue by bganglia** [bganglia/unpaywall-python#2]
This could probably use unpaywall_download_pdf_handle and then save to a file.

**Comment by naustica** [comment]
@bganglia Can you give me a use case for download_pdf_handle?

**Comment by bganglia** [comment]
@naustica I was downloading pdfs based on the doi and then extracting information from the PDF contents. Handles work well for PDFMiner, but if you are using command-line tools to process the downloaded PDFs, it is better just to save to a file right away.

**Comment by naustica** [comment]
ah ok thx.
