### ISSUE TITLE
Readthedocs site for first release

### ISSUE THREAD

**Issue by bganglia** [bganglia/unpaywall-python#23]
It would probably be enough just to use autodoc to get started

**Comment by naustica** [comment]
@bganglia ok, i started a changelog (https://github.com/unpywall/unpywall/blob/master/CHANGELOG.md). Maybe you can add something. Also, I have created a pre-release on github, can you take a look and change it if necessary?

**Comment by naustica** [comment]
@bganglia This needs to be done:

- [ ] cache
- [ ] data format
- [ ] error handling
- [ ] general check

(+) update changelog

**Comment by bganglia** [comment]
@naustica Thanks, I will use this list to organize the PR
