### ISSUE TITLE
Bring test coverage up to 80%

### ISSUE THREAD

**Issue by bganglia** [bganglia/unpaywall-python#26]
@naustica's suggestion from #12 

Here is a list of functions we may want to write tests for. Perhaps it does not make sense to have tests for all of them, so this list can be revised.

- [x] UnpywallCache.reset_cache
- [x] UnpywallCache.delete
- [x] UnpywallCache.timed_out - True
- [ ] UnpywallCache.timed_out - False
- [x] UnpywallCache.get - Present
- [x] UnpywallCache.get - Absent
- [x] UnpywallCache.save
- [x] UnpywallCache.save
- [x] UnpywallCache.load - File Present
- [x] UnpywallCache.load - File Absent
- [ ] UnpywallCache.download
- [x] Unpywall._progress (does it make sense to have a test for this?)
- [x] Unpywall.get_pdf_link
- [x] Unpywall.get_doc_link
- [x] Unpywall.get_all_links
- [x] Unpywall.download_pdf_handle
- [x] UnpwayllURL.url

Already added as of last release:
- [x] UnpywallCredentials.validate_email
- [x] Unpywall.get_df
- [x] Unpywall.get_json
- [x] Unpywall._validate_dois

**Comment by bganglia** [comment]
I am starting to write a few more in the more-unittests branch. I could also move this to a different branch or something if that is more convenient

**Comment by naustica** [comment]
@bganglia We should separate the tests similar to our package structure
/tests
- __init__.py
- test_unpywall.py
-test_cache.py

I would say that we need a maximum of one week to write the tests to answer your previous question from issue #12 .
There is still the `add_docstrings` branch. Do you need that?

Do you have access to https://codecov.io/gh/unpywall/unpywall/settings? If so, you can upload test reports using the token provided. But do not use the master for this unless for a release.

For help: https://docs.codecov.io/docs/about-the-codecov-bash-uploader

**Comment by bganglia** [comment]
@naustica 

Thanks, I will go ahead and separate the files.

I went ahead and deleted the ``add_docstrings`` branch just now.

It looks like I do have access, so I will check out the help link.

**Comment by bganglia** [comment]
@naustica I created a new `fix-cache` branch where I fix any issues I discover while writing tests. That way, if you want, you can merge those fixes into your branch without having to merge everything

**Comment by naustica** [comment]
@bganglia ok thanks.

**Comment by naustica** [comment]
Do you need help on this task? I would write unit tests for the cli next (probably in my cli branch?).

**Comment by bganglia** [comment]
Yes, CLI unittests would be great. You can help with the other ones if you would like, but I think I will be OK writing the cache testing functions.

**Comment by naustica** [comment]
@bganglia I can write the remaining tests for the unpywall class. But I would wait until you finish testing for the caching class.

**Comment by naustica** [comment]
@bganglia test coverage is currently at 88%.

**Comment by naustica** [comment]
@bganglia I implemented a backup cache to catch API calls while testing. But there is still work to be done.

**Comment by naustica** [comment]
@bganglia I think everything went well.

**Comment by naustica** [comment]
@bganglia For next release I would like to include monkeypatch for testing and also more configurations to cache (like option for path ...).

**Comment by naustica** [comment]
@bganglia Can you add a short release note to https://github.com/unpywall/unpywall/releases?

**Comment by bganglia** [comment]
@naustica Sure, I can add that. So should it just be like the one for v0.1.7.2, except for the new version?

**Comment by naustica** [comment]
@bganglia yup. Just mention the basic improvements.

**Comment by naustica** [comment]
@bganglia Similar to https://github.com/facebook/react-native/releases

**Comment by bganglia** [comment]
@naustica Should this version be a pre-release?

**Comment by naustica** [comment]
@bganglia make it a normal release, or? What would you say?

**Comment by naustica** [comment]
@bganglia the draft seems good.

**Comment by bganglia** [comment]
@naustica I agree, a normal release sounds good because all of the essential components are here.
