### ISSUE TITLE
Add more keywords to GitHub repo and on PyPi

### ISSUE THREAD

**Issue by naustica** [bganglia/unpaywall-python#28]
@bganglia Do you have any suggestions?

**Comment by bganglia** [comment]
Here are some possibilities:
``open access``
``full text``
``publisher data``
I will have to think about it some more.

**Comment by naustica** [comment]
sounds good to me. I will leave the issue open so that we can collect a few more ideas

**Comment by naustica** [comment]
Apparently, nobody uses publisher data as a keyword. I will ignore that.
